CURVE_ID = 'curve_id'
OBSERVATION_DATE = 'observation_date'
CONTRACT_START = 'contract_start'
EXPIRY_DATE = 'expiry_date'
DAYS_TO_EXPIRY = 'days_to_expiry'
VALUE = 'value'
LONG_SCREEN_NAME = 'long_screen_name'
CURRENCY = 'currency'
UOM = 'uom'

hdq_expression = '{method}(\'{symbol}\')'
