CURVE_ID = 'curve_id'
OBSERVATION_DATE = 'observation_date'
CONTRACT_START = 'contract_start'
EXPIRY_DATE = 'expiry_date'
DAYS_FROM_EXPIRY = 'days_from_expiry'
VALUE = 'value'
LONG_SCREEN_NAME = 'long_screen_name'
LEGEND = 'legend'
CURRENCY = 'currency'
UOM = 'uom'
SYMBOLS = 'symbols'
SYMBOL = 'symbol'
PROCESSOR = 'processor'

hdq_expression = '{method}(\'{symbol}\')'
